name: Coverage

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-tarpaulin
      - run: cargo tarpaulin --all --out Xml --timeout 300
      - uses: codecov/codecov-action@v3
        with:
          files: ./cobertura.xml
